### PR TITLE
attempting to cross-compile

### PR DESCRIPTION
**Pull request by marc-hanheide**
enabling arm64

### CODE REVIEW

**Comment by marc-hanheide** [comment]
This doesn't work as we can't cross compile with our NVIDA runtime on our self-hosted runner :-(

**Comment by cooperj** [comment]
Could we add the new Docker build into the standard non NVIDIA one ([docker-build.yaml](https://github.com/LCAS/ros-docker-images/blob/718d4701674fd0dea009fdef733bfd2e4e60fc05/.github/workflows/docker-build.yaml#L56))? This should be enough for the targeted Macs, obviously not ideal for future use cases…

However, would the [Dockerfile](https://github.com/LCAS/ros-docker-images/blob/main/Dockerfile) need updating to match the config of [Dockerfile.opengl](https://github.com/LCAS/ros-docker-images/blob/main/Dockerfile.opengl) - obviously omitting special NVIDIA/Cuda config?

**Comment by marc-hanheide** [comment]
Yes, @cooperj, problem is that currently our github action self-hoster runners are (on purpose) run on NVIDIA runtime, so we can use NVIDIA already at build time. We can of course build with standard github-hosted runners in a separate workflow. That may help with this at least to begin with, but as these builds take a long time we may run out of free minutes. So better may be to have a dedicated set of runners that are native arm64 and non-cuda. I can deploy some runners without nvidia runtime, and with cross compilation as a first instance. Or, better, if we had an arm64 linux box somewhere (but I guess we don't).

**Comment by marc-hanheide** [comment]
@pulver22 @gcielniak @cooperj 

You may all be interested in the PR. I managed to get cross compilation working. Once we merge this, our ROS base images are build also for `arm64` architectures. Now, I cannot test them easily, I can only check that they build. 

Also, due to the way they are built, the image tag is slightly different, as I had to add an `-arm64` suffix, as our Docker Registry cannot handle different architectures under the same tag if uploaded from different build processes (it's technical, but basically it created 2 different manifests and we had use 2 different runners at the moment, this can be improved at some point).

Anyway, what it means is that you can use this new base image (e.g. `lcas.lincoln.ac.uk/lcas/ros:jammy-humble-cuda12.2-opengl` for `amd64` as before or the new `lcas.lincoln.ac.uk/lcas/ros:jammy-humble-cuda12.2-opengl-arm64` for `arm64` (e.g. newer Macbooks) to build your own module iimage from. These *should* be able to run on any modern arm 64 bit system. IF (and that's a big IF) the host supports the NVIDIA runtime on arm64 then you should be able to even use 3D acceleration, but seriously doubt it.

**Comment by marc-hanheide** [comment]
Once we merge this, the new images are deployed and readily available.

Also pinging @ibrahimhroob to be aware that in the process I have streamlined the images a bit further and made them every so slightly leaner. Nothing in functionality has changes. They are just a few Mb smaller.

**Comment by marc-hanheide** [comment]
with blessings of @pulver22

**Pull request merged**
